services:
  postgres:
    image: postgres:16
    container_name: superheroops-postgres
    environment:
      POSTGRES_DB: superheroops
      POSTGRES_USER: superheroops
      POSTGRES_PASSWORD: superheroops
    ports:
      - "5433:5432"
    volumes:
      - superheroops-postgres-data:/var/lib/postgresql/data

volumes:
  superheroops-postgres-data:
