// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperHeroOps.Data;

#nullable disable

namespace SuperHeroOps.Data.Migrations
{
    [DbContext(typeof(SuperHeroOpsDbContext))]
    [Migration("20260911160807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperHeroOps.Core.CommunityArea", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_community_areas");

                    b.ToTable("community_areas", (string)null);
                });

            modelBuilder.Entity("SuperHeroOps.Core.CrimeIncident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Arrest")
                        .HasColumnType("boolean")
                        .HasColumnName("arrest");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_number");

                    b.Property<int>("CommunityAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("community_area_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_type");

                    b.HasKey("Id")
                        .HasName("pk_crime_incidents");

                    b.HasIndex("CommunityAreaId")
                        .HasDatabaseName("ix_crime_incidents_community_area_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_crime_incidents_occurred_at");

                    b.HasIndex("PrimaryType")
                        .HasDatabaseName("ix_crime_incidents_primary_type");

                    b.ToTable("crime_incidents", (string)null);
                });

            modelBuilder.Entity("SuperHeroOps.Core.Hero", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Alignment")
                        .HasColumnType("text")
                        .HasColumnName("alignment");

                    b.Property<int>("Combat")
                        .HasColumnType("integer")
                        .HasColumnName("combat");

                    b.Property<int>("Durability")
                        .HasColumnType("integer")
                        .HasColumnName("durability");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("pk_heroes");

                    b.ToTable("heroes", (string)null);
                });

            modelBuilder.Entity("SuperHeroOps.Core.HeroReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("community_area_id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer")
                        .HasColumnName("hero_id");

                    b.Property<string>("PredictedImpactNarrative")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("predicted_impact_narrative");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<string>("RiskAssessment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_assessment");

                    b.HasKey("Id")
                        .HasName("pk_hero_reports");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("ix_hero_reports_hero_id");

                    b.HasIndex("CommunityAreaId", "HeroId")
                        .HasDatabaseName("ix_hero_reports_community_area_id_hero_id");

                    b.ToTable("hero_reports", (string)null);
                });

            modelBuilder.Entity("SuperHeroOps.Core.InterventionScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("community_area_id");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("CrimeCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crime_category");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer")
                        .HasColumnName("hero_id");

                    b.Property<double>("NormalizedScore")
                        .HasColumnType("double precision")
                        .HasColumnName("normalized_score");

                    b.Property<double>("ProjectedEffectPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("projected_effect_percent");

                    b.HasKey("Id")
                        .HasName("pk_intervention_scores");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("ix_intervention_scores_hero_id");

                    b.HasIndex("CommunityAreaId", "HeroId")
                        .HasDatabaseName("ix_intervention_scores_community_area_id_hero_id");

                    b.ToTable("intervention_scores", (string)null);
                });

            modelBuilder.Entity("SuperHeroOps.Core.CrimeIncident", b =>
                {
                    b.HasOne("SuperHeroOps.Core.CommunityArea", "CommunityArea")
                        .WithMany("Incidents")
                        .HasForeignKey("CommunityAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_crime_incidents_community_areas_community_area_id");

                    b.Navigation("CommunityArea");
                });

            modelBuilder.Entity("SuperHeroOps.Core.HeroReport", b =>
                {
                    b.HasOne("SuperHeroOps.Core.CommunityArea", "CommunityArea")
                        .WithMany("Reports")
                        .HasForeignKey("CommunityAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hero_reports_community_areas_community_area_id");

                    b.HasOne("SuperHeroOps.Core.Hero", "Hero")
                        .WithMany("Reports")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hero_reports_heroes_hero_id");

                    b.Navigation("CommunityArea");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("SuperHeroOps.Core.InterventionScore", b =>
                {
                    b.HasOne("SuperHeroOps.Core.CommunityArea", "CommunityArea")
                        .WithMany("Scores")
                        .HasForeignKey("CommunityAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_scores_community_areas_community_area_id");

                    b.HasOne("SuperHeroOps.Core.Hero", "Hero")
                        .WithMany("Scores")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_scores_heroes_hero_id");

                    b.Navigation("CommunityArea");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("SuperHeroOps.Core.CommunityArea", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Reports");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("SuperHeroOps.Core.Hero", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
