using SuperHeroOps.Core;

namespace SuperHeroOps.Data;

// The 77 fixed Chicago community areas, per the Chicago Data Portal's "Boundaries -
// Community Areas" reference list. Loaded once alongside crime ingestion so areas with
// zero incidents in the trailing 90-day window still show up in the neighborhood list.
public static class ChicagoCommunityAreas
{
    public static IReadOnlyList<CommunityArea> All { get; } =
    [
        new() { Id = 1, Name = "Rogers Park" },
        new() { Id = 2, Name = "West Ridge" },
        new() { Id = 3, Name = "Uptown" },
        new() { Id = 4, Name = "Lincoln Square" },
        new() { Id = 5, Name = "North Center" },
        new() { Id = 6, Name = "Lake View" },
        new() { Id = 7, Name = "Lincoln Park" },
        new() { Id = 8, Name = "Near North Side" },
        new() { Id = 9, Name = "Edison Park" },
        new() { Id = 10, Name = "Norwood Park" },
        new() { Id = 11, Name = "Jefferson Park" },
        new() { Id = 12, Name = "Forest Glen" },
        new() { Id = 13, Name = "North Park" },
        new() { Id = 14, Name = "Albany Park" },
        new() { Id = 15, Name = "Portage Park" },
        new() { Id = 16, Name = "Irving Park" },
        new() { Id = 17, Name = "Dunning" },
        new() { Id = 18, Name = "Montclare" },
        new() { Id = 19, Name = "Belmont Cragin" },
        new() { Id = 20, Name = "Hermosa" },
        new() { Id = 21, Name = "Avondale" },
        new() { Id = 22, Name = "Logan Square" },
        new() { Id = 23, Name = "Humboldt Park" },
        new() { Id = 24, Name = "West Town" },
        new() { Id = 25, Name = "Austin" },
        new() { Id = 26, Name = "West Garfield Park" },
        new() { Id = 27, Name = "East Garfield Park" },
        new() { Id = 28, Name = "Near West Side" },
        new() { Id = 29, Name = "North Lawndale" },
        new() { Id = 30, Name = "South Lawndale" },
        new() { Id = 31, Name = "Lower West Side" },
        new() { Id = 32, Name = "Loop" },
        new() { Id = 33, Name = "Near South Side" },
        new() { Id = 34, Name = "Armour Square" },
        new() { Id = 35, Name = "Douglas" },
        new() { Id = 36, Name = "Oakland" },
        new() { Id = 37, Name = "Fuller Park" },
        new() { Id = 38, Name = "Grand Boulevard" },
        new() { Id = 39, Name = "Kenwood" },
        new() { Id = 40, Name = "Washington Park" },
        new() { Id = 41, Name = "Hyde Park" },
        new() { Id = 42, Name = "Woodlawn" },
        new() { Id = 43, Name = "South Shore" },
        new() { Id = 44, Name = "Chatham" },
        new() { Id = 45, Name = "Avalon Park" },
        new() { Id = 46, Name = "South Chicago" },
        new() { Id = 47, Name = "Burnside" },
        new() { Id = 48, Name = "Calumet Heights" },
        new() { Id = 49, Name = "Roseland" },
        new() { Id = 50, Name = "Pullman" },
        new() { Id = 51, Name = "South Deering" },
        new() { Id = 52, Name = "East Side" },
        new() { Id = 53, Name = "West Pullman" },
        new() { Id = 54, Name = "Riverdale" },
        new() { Id = 55, Name = "Hegewisch" },
        new() { Id = 56, Name = "Garfield Ridge" },
        new() { Id = 57, Name = "Archer Heights" },
        new() { Id = 58, Name = "Brighton Park" },
        new() { Id = 59, Name = "McKinley Park" },
        new() { Id = 60, Name = "Bridgeport" },
        new() { Id = 61, Name = "New City" },
        new() { Id = 62, Name = "West Elsdon" },
        new() { Id = 63, Name = "Gage Park" },
        new() { Id = 64, Name = "Clearing" },
        new() { Id = 65, Name = "West Lawn" },
        new() { Id = 66, Name = "Chicago Lawn" },
        new() { Id = 67, Name = "West Englewood" },
        new() { Id = 68, Name = "Englewood" },
        new() { Id = 69, Name = "Greater Grand Crossing" },
        new() { Id = 70, Name = "Ashburn" },
        new() { Id = 71, Name = "Auburn Gresham" },
        new() { Id = 72, Name = "Beverly" },
        new() { Id = 73, Name = "Washington Heights" },
        new() { Id = 74, Name = "Mount Greenwood" },
        new() { Id = 75, Name = "Morgan Park" },
        new() { Id = 76, Name = "O'Hare" },
        new() { Id = 77, Name = "Edgewater" },
    ];
}
